#!/usr/bin/env perl

sub Usage {
    die <<"EOT";
\nUsage: $0 FASTAFILE N

    $0 splits FASTAFILE in files with N sequences

EOT
}

($#ARGV == 1) || Usage;

$infile = $ARGV[0];
$max = $ARGV[1];

open INFILE,$infile or die "Can't open $infile: $!";

$cnt = 1;
$i = 1;
$outfile = $ARGV[0]. ".$cnt";

open (OUT,">$outfile") || die "cannot open $outfile: $!";
while (<INFILE>) {
    if ($_ =~ /^>/) {
	s/ +/ /g;
	if ($i > $max) {
	    close OUT;
	    $cnt++;
	    $i = 1;
	    $outfile = "$infile.$cnt";
	    open (OUT,">$outfile") || die "cannot open $outfile: $!";
	}
	$i++;
	print OUT;
    }
    else {
        print OUT;
    }
}

close INFILE;
close OUT;
